/***************************************************************************//**
* \file TEST_MODEL_tflm_x_data_int8x8.h
*
* \brief
* Autogenerated with ml-coretools, this file contains input data
* for the TEST_MODEL model in int8x8 representation.
* Date: 2026-07-08 16:21:38.198918+02:00
*******************************************************************************
* (c) 2019-2026, Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
*******************************************************************************
* This software, including source code, documentation and related materials
* (&#34;Software&#34;), is owned by Cypress Semiconductor Corporation or one of its
* subsidiaries (&#34;Cypress&#34;) and is protected by and subject to worldwide patent
* protection (United States and foreign), United States copyright laws and
* international treaty provisions. Therefore, you may use this Software only
* as provided in the license agreement accompanying the software package from
* which you obtained this Software (&#34;EULA&#34;).
*
* If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
* non-transferable license to copy, modify, and compile the Software source
* code solely for use in connection with Cypress&#39;s integrated circuit products.
* Any reproduction, modification, translation, compilation, or representation
* of this Software except as specified above is prohibited without the express
* written permission of Cypress.
*
* Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT, IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. Cypress
* reserves the right to make changes to the Software without notice. Cypress
* does not assume any liability arising out of the application or use of the
* Software or any product or circuit described in the Software. Cypress does
* not authorize its products for use in any products where a malfunction or
* failure of the Cypress product may reasonably be expected to result in
* significant property damage, injury or death (&#34;High Risk Product&#34;). By
* including Cypress&#39;s product in a High Risk Product, the manufacturer of such
* system or application assumes all risk of such use and in doing so agrees to
* indemnify Cypress against all liability.
*******************************************************************************/

#ifndef TEST_MODEL_TFLM_X_DATA_INT8X8_H
#define TEST_MODEL_TFLM_X_DATA_INT8X8_H

#include <stdint.h>


extern const uint8_t TEST_MODEL_x_data_bin[];
#define TEST_MODEL_X_DATA_BIN_LEN (78416)

#endif // TEST_MODEL_TFLM_X_DATA_INT8X8_H